### ISSUE TITLE
Dark theme color for "danger" container

### ISSUE THREAD

**Issue by madooei** [emersonbottero/vitepress-dark-theme#2]
For [custom containers](https://vitepress.vuejs.org/guide/markdown.html#custom-containers), the colors adjust in the dark theme except for the "danger" container. 

![2022-01-27_23-22-29 (1)](https://user-images.githubusercontent.com/1509757/151486979-7abfc70c-c964-4a0b-bd40-2b2efcd6cb86.gif)

If I knew how to fix it, I would make a PR. Sorry, I can't map your [dark-theme.css](https://github.com/emersonbottero/vitepress-dark-theme/blob/main/dark-theme.css) vars and the ones used for this purpose.

**Comment by emersonbottero** [comment]
fixed.

**Comment by madooei** [comment]
I tried this and to my eyes, it looks better!

```css
body.dark-mode .custom-block.danger {
  background-color: #6e4f4fd2;
  color: #f5d3d3;
}

body.dark-mode .custom-block.danger .custom-block-title {
  color: #f6b9b9;
}
```
![2022-01-29_12-26-47 (1)](https://user-images.githubusercontent.com/1509757/151670934-fe5c7fc5-9c3d-4d8d-be06-d1022a949cae.gif)
